# Generated by Django 5.0.6 on 2024-06-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Translation",
            new_name="Input_text",
        ),
    ]
